---
name: rotate-openrouter-key
display_name: "Rotate OpenRouter Key"
description: Safely rotate the OpenRouter API key across all config files in an OpenClaw installation. Finds every location, updates them, restarts the gateway, and verifies.
version: 1.0.0
triggers:
  - rotate openrouter key
  - change openrouter key
  - update openrouter api key
  - replace openrouter key
  - openrouter 401 error
  - fix openrouter authentication
